### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by DanielMSchmidt** [mgechev/aspect.js#14]
Hi there,

First of all thanks for this library, it looks like a great approach concerning AOP in JS and TypeScript sure seems to be the best fit for this kind of libs. I am really looking forward evaluating it for my master thesis.

Just one question: Do you have any metrics / benchmarks on the performance overhead of your library?

Thanks for your help

P.S.: If the performance works for me I will use this library, so if you have any tasks concerning the further development don't hesitate to reach out to me, I would be glad to help.

**Comment by mgechev** [comment]
Hey @DanielMSchmidt. I don't have any benchmarks, however, I'd love to assist you in developing some.

I'd recommend you to use [benchpress](https://github.com/angular/benchpress). I can help you with the setup, let me know what scenarios you want to test.

**Comment by DanielMSchmidt** [comment]
Great to hear, thanks a lot! I will try it myself and let you know as soon as there is any progress. Would you like to see this in another repo or a subfolder in this one?

**Comment by mgechev** [comment]
Both work for me. If it is easier to work in a separate repo it is fine.
