### ISSUE TITLE
Work with mangling

### ISSUE THREAD

**Issue by mgechev** [mgechev/aspect.js#15]
Currently the joint-points are declared with regular expressions:

``` ts
export interface MethodSelector {
  classNamePattern: RegExp;
  methodNamePattern: RegExp;
}
```

``` ts
export interface MemberSelector {
  classNamePattern: RegExp;
  fieldNamePattern: RegExp;
}
```

This will prevent the library work with mangled production build.

Possible solutions:
- Introduce "production" mode as part of the build process into which the code will be woven in-place (i.e. we will inject code on the place of the joint point).
  - Drawbacks:
    - Code duplication (given advice needs to be copied each place we use it).
    - Need to generate sourcemaps.
    - Complicated.
- Pass a list of classes and their methods:
  
  ``` ts
  class Bar {
    foo() {
      return 2;
    }
    baz() {
      return 42;
    }
  } 
  
  Bar.prototype.foo;
  Bar.prototype.baz;
  ```
  - Drawbacks:
    - Couples the advice with all the places it is used in more explicitly.
    - Need to alter existing API.
    - More verbose.

**Comment by mgechev** [comment]
Option 2 seems reasonable at this point.

**Comment by SamVerschueren** [comment]
The benefit of 2 would also be that you can drop the `@Wove()` decorator. This way, the woven classes/method now nothing about them being part of an aspect.

**Comment by SamVerschueren** [comment]
Great work @mgechev ! :beers:

**Comment by mgechev** [comment]
I'd love to introduce build-time woving one day... :smile:

**Comment by SamVerschueren** [comment]
That would be super cool!
