### ISSUE TITLE
Constructor joint point

### ISSUE THREAD

**Issue by SamVerschueren** [mgechev/aspect.js#27]
Working on this already. Little bit harder than the rest so I'll keep you posted :).

**Comment by mgechev** [comment]
Another possible complication is issues for AoT compiled Angular app.

We can have a conversation how to apply compile-time weaving in order to solve the issue.

**Comment by SamVerschueren** [comment]
Haven't thought about that. This might not work correctly in AoT.

> We can have a conversation how to apply compile-time weaving

Cool! Let me know which channel you prefer (GitHub, Google Hangouts, Skype, Twitter DM, ...).

**Comment by mgechev** [comment]
We can try [gitter](https://gitter.im/mgechev)?

**Comment by SamVerschueren** [comment]
Sure! I'm on Gitter, not sure how I can make contact to you though...
