### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by SamVerschueren** [mgechev/aspect.js#28]
After upgrading my dependencies to `angular@2.4`. I started receiving the following error when I do AoT compilation.

> Error: Error encountered resolving symbol values statically. Could not resolve aspect.js relative to /Users/sam/Projects/pridiktiv/
frontend/medapp/dist/tmp/app/shared/async-services/aws.async-service.ts.

I import Aspect.js like this

```js
import { Wove } from 'aspect.js';
```

And I can resolve the issue by importing it like this

```js
import { Wove } from 'aspect.js/aspect.js';
```

I use your seed project so I upgraded my [`compile.ahead.prod.ts`](https://github.com/mgechev/angular-seed/blob/master/tools/tasks/seed/compile.ahead.prod.ts) to the one in the Seed project.

Do you have any ideas as to what is causing this issue? It worked perfectly before I did the upgrade. Don't have any issues with other libraries either.

**Comment by mgechev** [comment]
The main file in the seed's SystemJS configuration is not set.

**Comment by SamVerschueren** [comment]
It doesn't use the SystemJS config when running AoT, or is it?

**Comment by SamVerschueren** [comment]
I mean while running the build step off course.

**Comment by mgechev** [comment]
@SamVerschueren I believe this is an issue in the `@angular/compiler-cli`.

- Here's the issue I opened https://github.com/angular/angular/issues/14663.
- Here's PR with fix https://github.com/angular/angular/pull/14664.
