### ISSUE TITLE
How to retrieve the call chain / stack trace in the aspect?

### ISSUE THREAD

**Issue by andrashatvani** [mgechev/aspect.js#30]
I've got a LoggerAspect, an HttpService and many components and services which use the HttpService. How can I retrieve the HttpService caller's name in the LoggerAspect?

**Comment by mgechev** [comment]
You can find the caller of the HttpService without creating a specific instance of the HttpService for each individual consumer, or passing the consumer as argument.

If you have:

```ts

const HttpService = { get: () => {} }

const Consumer = {
  makeRequest() {
    HttpService.get();
  }
};

Consumer.makeRequest();

```
There's no way to know if `Consumer` delegated it's call to `HttpService` or not.

**Comment by andrashatvani** [comment]
I've found https://www.stacktracejs.com/#!/docs/stacktrace-js - wouldn't that be an option?
