### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by ishandutta2007** [mgechev/aspect.js#31]
On starting the node server I get the following error
> my/path/to/nodemodules/node_modules/aspect.js/src/joint_points/method_call.js:62
>             pointcut.advice = new constr(target, descriptor.value);
>                                                            ^
> TypeError: Cannot read property 'value' of undefined

Steps followed:
1. `npm install aspect.js --save`

2. Opened of of my controller.ts and added the following code on top

```
import {
  Metadata,
  MethodMetadata,
  Wove,
  afterGetter,
  afterMethod,
  afterSetter,
  beforeGetter,
  beforeMethod,
  beforeStaticMethod,
} from 'aspect.js';

class LoggerAspect {
  @beforeMethod({
    classNamePattern: /.*Controller/,
    methodNamePattern: /.*/
  })
  invokeBeforeMethod(meta: Metadata) {
    console.log(`Inside of the logger`);
  }
}

```

  3.Added the decorator in the same file as follows

```
@Wove()
class MyController {
  mymethod() {}
}
```

4. `tsc`

5. `node app.js`

**Comment by SamVerschueren** [comment]
Odd, it works fine for me

### index.ts
```js
import { beforeMethod, Wove } from 'aspect.js';

class LoggerAspect {
  @beforeMethod({
    classNamePattern: /.*Controller/,
    methodNamePattern: /.*/
  })
  invokeBeforeMethod(meta: Metadata) {
    console.log('Inside the logger');
  }
}

@Wove()
class MyController {

  foo() {
    console.log('Inside the controller');
  }
}

const controller = new MyController();
controller.foo();
```

## tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "removeComments": true,
    "noImplicitAny": false,
    "outDir": "dist"
  },
  "exclude": [
    "node_modules"
  ]
}
```

1. `tsc`
2. `node dist/index.js`

> Inside the logger
> Inside the controller

-----------------------
What's your TypeScript version? `tsc --version`

**Comment by mgechev** [comment]
@SamVerschueren thanks for the response!

**Comment by SamVerschueren** [comment]
No problem, glad I can help you out!
