### ISSUE TITLE
doubt about features

### ISSUE THREAD

**Issue by ciroreed** [mgechev/aspect.js#32]
This library actually supports calling synchronous multiple chained aspects? 

IE: 

@an-aspect-which-check-if-user-is-logged
@an-aspect-which-serializes-the-current-instance-to-json
@an-aspect-which-perform-http-post-to-save-returned-instance-from-the-previous-aspect
[method called saveUser with business logic]

```javascript
class User {
   ...
   @auth //cross cutting concern
   @serialize //cross cutting concern
   @POSTInstance //cross cutting concern
   saveUser() {
      //output some where 
   }
   ...
}
```

**Comment by mgechev** [comment]
@ciroreed, using the `MethodMetadata` you get the method's return result, so it is responsibility of the aspects to support async calls.

I kept the API minimalistic and introduced only the minimal set of joint points.

**Comment by ciroreed** [comment]
Thanks, but i read the examples and I didnt see how decorated methods will wait for their predecessor to be finished before call themselves.

IE: 

```javascript
class User {
   ...
   @auth [evaluates first .. called last]
   @serialize [evaluates second .. called within]
   @POSTInstance [evaluates last ... called first]
   saveUser() {
      //output some where 
   }
   ...
}
```
it evaluates the expressions in declaration order, but flips code 
somehow the source code under-the-hood will be:

```javascript
User.prototype.saveUser = function(){
//POSTinstance
   function(){
     //serialize 
      function(){
         //auth 
            function(){
               //original method
               function (){

               }
           }
      }
  }
}
```

doesn't it? if so, can you provide an example or instruction to avoid this? any help appreciated :)

**Comment by mgechev** [comment]
Lets suppose we have nested `before` aspects, once the top advice makes an async call it can wait until the promise is resolved until it proceeds the call, etc.

This is what happens, and you can imagine that inside of the nested callbacks you can have logic for handling async calls:

```js
User.prototype.saveUser = function(){
//POSTinstance
   function(){
     //serialize 
      function(){
         //auth 
            function(){
               //original method
               function (){

               }
           }
      }
  }
}
```

**Comment by SamVerschueren** [comment]
@mgechev What I think that he's saying is that the aspects aren't running in the correct order. They are declared like this

1. auth
2. serialize
3. POSTinstance

While they are now being executed like

1. POSTInstance
2. serialize
3. auth

**Comment by mgechev** [comment]
In such case:

```ts
class User {
   ...
   @auth //cross cutting concern
   @serialize //cross cutting concern
   @POSTInstance //cross cutting concern
   saveUser() {
      //output some where 
   }
   ...
}
```

This is really not the syntax for using aspect.js. The order of execution completely depends on the side-effect imports of the aspects.

**Comment by ciroreed** [comment]
Thanks @mgechev @SamVerschueren 

So you're used to handle async calls in at the decorator fn. You mean that `POSTinstance` has to deal itself with another crosscutting-concern, which in this case is serialize, don't you?

I would be nice to declare independent aspects which are able to run synchronously before or after the decorated method. So the `aspect` concept is fully independent of infrastructure logic

**Comment by ciroreed** [comment]
"Lets suppose we have nested before aspects, once the top advice makes an async call it can wait until the promise is resolved until it proceeds the call, etc"

How i can define an aspect without knowledge of their position in the call stack. Or if the preceding call is async or not?
