### ISSUE TITLE
Interceptinn promises

### ISSUE THREAD

**Issue by dpinart** [mgechev/aspect.js#35]
Hi

I've seen afterReject and afterResolve decorators in introduction post of the library [here](http://blog.mgechev.com/2015/07/29/aspect-oriented-programming-javascript-aop-js/) that I guess they are useful to intercept async methods but they are not present in the library. How can I intercept promise rejections?

Thanks

**Comment by mgechev** [comment]
Hey! You can achieve this result with the following construct:

```
class Aspect {
  @after({
    methodNamePatter: /Target/,
    methodNamePatterns: [/async/]
  })
  afterAsync(meta) {
    meta.method.result.then(() => {
      console.log('Equivalent to afterResove');
    });
  }
}

@Wove()
class Target {
  async() {
    return Promise.resolve(42);
  }
}
```
