### ISSUE TITLE
beforeMethod and afterMethod does not capture constructor calls

### ISSUE THREAD

**Issue by muzaffar-omer** [mgechev/aspect.js#38]
Hi,
      Kindly, I configured one aspect (called it Logger), as a provider below:

import { Injectable } from '@angular/core';
import {beforeMethod, Metadata, afterMethod} from 'aspect.js';

@Injectable()
export class Logger {
  constructor()
  {
    console.log(`Just initialized the logger ...`);
  }
  
  @beforeMethod({
    classNamePattern: /^.*/,
    methodNamePattern: /^.*/
  })
  invokeBeforeMethod(meta: Metadata)
  {
      console.log(`Before calling ${meta.method.name}`);
  }

  @afterMethod({
    classNamePattern: /^.*/,
    methodNamePattern: /^.*/
  })
  invokeAfterMethod(meta: Metadata)
  {
      console.log(`After calling ${meta.method}`);
  }
}

also configured it in the app.module.ts 

import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { Logger } from '../providers/logger'

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    Logger,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {

  constructor(public logger: Logger){}
}

But I observed Logger does not capture constructors calls. Is anything special required to be able to capture the initialization of objects. Or we don't support constructors calls?

Thank you,

**Comment by mgechev** [comment]
Constructor calls are not yet supported (here's [the roadmap](https://github.com/mgechev/aspect.js#roadmap)). If you have time, would appreciate a PR!

**Comment by SamVerschueren** [comment]
I tried it before and I think it's almost impossible to do. At least at that time I wasn't able to figure it out. Maybe I should take another look.

Another approach that @mgechev and I discussed before is using Babel and/or TypeScript plugins to actually inject the code at the correct places. Didn't find the time to actually look into that approach but it's in my todo :).

**Comment by muzaffar-omer** [comment]
Thanks a lot @mgechev  and @SamVerschueren for your reply :) ... the current features are more than enough for my current development :)

Really thanks for making our lives easier by this library ...

@mgechev yes sure, I will post a PR

Thanks All !
