### ISSUE TITLE
Has NPM package been updated to contain this PR (feat: automatically weave classes)?

### ISSUE THREAD

**Issue by thaoula** [mgechev/aspect.js#48]
Hi @mgechev,

Thanks for your library. I am just starting to try and use it in a Node app and it seems to work fine.

I was looking though the closed issues and I see this feature -
feat: automatically weave classes
https://github.com/mgechev/aspect.js/pull/45

However, when i try and use the classes property mentioned it does nothing. 

The package.json file was updated 3 months ago and the merge only occurred 22 days ago..

So question is, has the NPM package been updated?

Regards,
Tarek

**Comment by SamVerschueren** [comment]
No it hasn't been updated since then. Hold on for a little moment, I'm sure @mgechev will publish it soon :). He probably just forgot.

**Comment by mgechev** [comment]
Excuse me for the delay. aspect.js@0.6.0 is now published.
