### ISSUE TITLE
@deprecated annotation

### ISSUE THREAD

**Issue by Attrash-Islam** [mgechev/aspect.js#52]
Hi Minko,
Are you planning to implement the generic decorators? What features you're planning to add here?

I thought of implementing (Sending PR) the @deprecated to console.warn a deprecation warning on the console since it globally used in Aspect oriented languages like: Java.

Any interest in that?
Thanks

**Comment by Attrash-Islam** [comment]
Or https://github.com/jayphelps/core-decorators should be the answer?

**Comment by mgechev** [comment]
Yes, use `core-decorators`. You can take advantage of `aspect.js` in order to use the AOP paradigm in your application development.
