### ISSUE TITLE
JavaScript syntax extended classes

### ISSUE THREAD

**Issue by Markus-Harr** [mgechev/aspect.js#53]
Hi,
thanks you, this library is great.
Unfortunately I've problems with logging of extended classes.

Depending where I use @Wove() only methods off one class are logged (either foo or bar), but I don't get both logged together if constructor is executed. If both classes use wove decorator or only ClassA uses decorator => foo is logged. If only ClassB uses decorator => bar is logged. 

file classB.js
```javascript
import {Wove} from 'aspect.js';

@Wove()
export default class ClassB extends ClassA {

    constructor() {
        this.foo();
        this.bar();
    }

    bar() {
        ...
    }
    ...
}
```

file classA.js
```javascript
import {Wove} from 'aspect.js';

@Wove()
export default ClassA {
    foo() {
        ...
    }
    ...
}
```

file logger.js
```javascript
import {
  beforeMethod,
} from 'aspect.js';

export default class LoggerAspect {
  @beforeMethod({
      methodNamePattern: /.*/,
      classNamePattern: /.*/
  })
  beforeLogger(meta, ...args) {
      ...
  }
...
}
```

What is the correct syntax for this case?

**Comment by mgechev** [comment]
Really good catch! I will push a fix in a bit.

**Comment by mgechev** [comment]
This was the fix https://github.com/mgechev/aspect.js/commit/be529e317939ac13b3390cefd6a4e4432bbacce6#diff-1ba746b3fa1602a2aa41de09ac00f034R4.
