### ISSUE TITLE
Set Up on Browser

### ISSUE THREAD

**Issue by bernardmizzi** [mgechev/aspect.js#54]
I would like to use this library. How do I set it up to use it on the browser? Do I have to download something?

**Comment by mgechev** [comment]
You need to install it and require it in your JavaScript files:

1. Install:

```shell
npm i aspect.js --save
```

2. Require:

```js
import * as aop from 'aspect.js';

// ...
```

**Comment by bernardmizzi** [comment]
I'm still having an issue, do you think that this is the right way to use it on  the browser?

**Comment by bernardmizzi** [comment]
I'm getting 'unexpected *' as an error

**Comment by SamVerschueren** [comment]
Make sure you are using a tool like Webpack or transpile your code with TypeScript in order to make it work in the browser.

**Comment by bernardmizzi** [comment]
Sorry for disturbing again but how can you bundle a folder with Webpack? All I found were methods to bundle JS files and not folders and for aspect.js I require the whole folder aspect.js.

**Comment by bernardmizzi** [comment]
I would like to use this library for my dissertation and I currently need this asap

**Comment by bernardmizzi** [comment]
I managed to bundle the code into one big Javascript file by using browserify. Then I'm including the bundled file in the html file as a module and I'm getting `The requested module does not provide an export named 'default'`. Any help would be appreciated
