### ISSUE TITLE
How is AOP achieved?

### ISSUE THREAD

**Issue by bernardmizzi** [mgechev/aspect.js#55]
So does this library make use of instrumentation?

**Comment by bernardmizzi** [comment]
I mean like for example for every function you declare a new function like `window[nameOfFunction] = function(){ ... }`

**Comment by mgechev** [comment]
You can either look at [this article](http://blog.mgechev.com/2015/07/29/aspect-oriented-programming-javascript-aop-js/) or at the source code for more details.
