### ISSUE TITLE
How can i exclude certain method inside component? or is there any method level annotation like @Wove?

### ISSUE THREAD

**Issue by kailashthakuri** [mgechev/aspect.js#56]

**Comment by kailashthakuri** [comment]
![classlevel](https://user-images.githubusercontent.com/17194118/38796779-2ad7d576-417c-11e8-8744-17cbcc4caba8.PNG)

Here, @Wove is used in component level that intercept all methods of that component. My requirement is to intercept certain method of that component.
Is there any annotation for method level that intercept only that method.
![method](https://user-images.githubusercontent.com/17194118/38796880-833e4e5c-417c-11e8-921c-9c2c21cd29fc.PNG)

**Comment by SamVerschueren** [comment]
In your aspect, use the `@beforeMethod` or any other decorator that suits your needs. See the [example](https://github.com/mgechev/aspect.js#sample-usage).

```ts
class SigninComponentAspect {
  @beforeMethod({
    classes: [SigninComponent],
    methodNamePattern: /^submitForm$/
  })
  invokeBeforeMethod(meta: Metadata) {
    // Handle stuff
  }
}
```
