### ISSUE TITLE
Proposal: Change name of decorator "Wove" to something better

### ISSUE THREAD

**Issue by matthewadams** [mgechev/aspect.js#67]
I find the name `Wove` nonintuitive for that decorator.  The English simple past participle `wove` doesn't really fit here and causes it to read awkwardly.

Better names, IMHO, include (but are not necessarily limited to):
* `Advised`
* `Woven`

Once a better name is chosen, backward compatibility could be provided by aliasing `Wove` and deprecating its usage in favor of the new name.

**Comment by matthewadams** [comment]
After adding a few issues, PRs, etc, I've noticed that the term "wove" is used incorrectly in many places throughout the codebase.  This issue should probably be increased in scope to address all usages of the word "wove".

**Comment by mgechev** [comment]
I'd suggest releasing 0.8.0 once we have this issue resolved.

**Comment by mgechev** [comment]
If you find anything else which requires refactoring, feel free to open a PR.

**Comment by matthewadams** [comment]
@mgechev, These changes in https://github.com/mgechev/aspect.js/commit/ffa52fa73f639e6da945c8674e2cbc91998d4c8f break backward compatibility AFAICT.  I was assuming that this project abides by [`semver`](https://www.semver.org] versioning semantics, so a breaking change necessitates a major version bump.

I'm not sure what you mean by "I'd suggest releasing 0.8.0 once we have this issue resolved."  I feel that you should release `0.8.0` now, because it adds a new feature & fixes a bug, but is otherwise backward compatible with `0.7.5`.  I feel that these changes should cause the version to go to `1.0.0`.

**Comment by mgechev** [comment]
Yes, I wrote this comment before [this one](https://github.com/mgechev/aspect.js/issues/69#issuecomment-439720261). Once we're happy with the current state of aspect.js, I'll publish 1.0.0.

**Comment by matthewadams** [comment]
Ah, ok, gotcha.  :)
