### ISSUE TITLE
class name return wrong name that return "n"

### ISSUE THREAD

**Issue by ahmedalattar** [mgechev/aspect.js#83]
when i build the project angular application with aspect the method name return right but the class name returned n just only n in all classes name 

![image](https://user-images.githubusercontent.com/12754034/66553545-9d8f4e80-eb4b-11e9-9192-c7bfe6d4abb6.png)

**Comment by mgechev** [comment]
Is this after `ng build --prod`? My guess is that the minified has mangled your code and renamed the method.

**Comment by ahmedalattar** [comment]
first i really thank you very mush for your amazing effort and your quick reply .
you are right that happen after ng build --prod and deploy it in wildfly server
i don,t know why really this happen in class name and doesn't,t happen in method name why class ?

**Comment by mgechev** [comment]
The minifier has its own heuristic on how not to break your code. I'll close the issue here since it doesn't seem related to aspect.js.

**Comment by ahmedalattar** [comment]
i take this way to stop the minifier with "ng build --build-optimizer=false" and everything work right 
![successPNG](https://user-images.githubusercontent.com/12754034/66630851-52397680-ec05-11e9-9137-ed049976abc1.PNG)

but i have another question when the args return [object Objecrt] any way to display the content of this object  i try json.stringify but not work ???

**Comment by mgechev** [comment]
It's not a good idea to disable the build optimizer. I'd recommend you to instead of relying on the symbol name use the reference. If you disable the optimizer you'll make your app load faster.

**Comment by ahmedalattar** [comment]
please i don,t understand your meaning if you can give me example to use reference instead of use name of class ??
