### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by designeng** [mgechev/aspect.js#9]
npm install -g babel-node
Error: 'babel-node' is not in the npm registry.

**Comment by mgechev** [comment]
Thanks for pointing this out! `aspect.js` is still in *very* early stage, it's good for playing around with it.

**Comment by designeng** [comment]
Yes, but I think it's brilliant. But apparently there is another issue with demo: may be it's not so obvious how to get demo/index.js from demo/index.ts with current gulpfile.

**Comment by mgechev** [comment]
I'll update the repo completely next a couple of days. I'd love to hear your feedback! :-)

**Comment by mgechev** [comment]
@designeng you can clone the repo and follow the instructions in the readme.md file.

Everything should work properly.

**Comment by designeng** [comment]
@mgechev, thanks, perfect!
